# Generated by Django 4.2.5 on 2023-09-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaTarefaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AtividadeAndre.disciplinamodel')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricão', models.CharField(max_length=255)),
                ('data_entrega', models.CharField(max_length=10)),
                ('concluido', models.BooleanField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AtividadeAndre.alunomodel')),
                ('disciplina', models.ManyToManyField(blank=True, related_name='tags', through='AtividadeAndre.DisciplinaTarefaModel', to='AtividadeAndre.disciplinamodel')),
            ],
        ),
        migrations.AddField(
            model_name='disciplinatarefamodel',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AtividadeAndre.tarefamodel'),
        ),
    ]
